version: 2.1

jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/circleci-reactive-countries
    docker: # run the steps with Docker
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: m2-{{ checksum "pom.xml" }}
      - run: mvn package -Dskip.unit.test=true -Dskip.integration.test=true
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}
  unit_tests:
    working_directory: ~/circleci-reactive-countries
    docker: # run the steps with Docker
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: m2-{{ checksum "pom.xml" }}
      - run: ./mvnw test
      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
    #    # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/surefire-reports
  integration_tests:
    working_directory: ~/circleci-reactive-countries
    docker: # run the steps with Docker
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: m2-{{ checksum "pom.xml" }}
      - run: ./mvnw integration-tests -Dskip.unit.test=true
      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          #    # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/failsafe-reports

workflows:
  build_and_test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - integration_tests:
          requires:
            - build